language: node_js
node_js:
- '12'
before_install:
- ls
- chmod +x aws_credential_travis.sh
- "./aws_credential_travis.sh"
- cd lambda/householdList
- npm install -g ask-cli
- npm install -g aws-sdk
script:
- npm test
after_success:
- cd ../..
- ls -a
- ls .ask -a
- ask deploy
