language: node_js
node_js:
- '12'
before_install:
- chmod +x credential_travis.sh
- "./credential_travis.sh"
- cd lambda/householdList
- npm install -g ask-cli@^1.0.0
- npm install -g aws-sdk
- curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
- unzip awscli-bundle.zip
- ./awscli-bundle/install -b ~/bin/aws
- export PATH=~/bin:$PATH

script:
- npm test
after_success:
- cd ../..
- chmod +x hooks/pre_deploy_hook.sh
- ask deploy --debug
