language: node_js
node_js:
- '12'
before_install:
- ls
- chmod +x credential_travis.sh
- "./credential_travis.sh"
- cd lambda/householdList
- npm install -g ask-cli@^1.0.0
- npm install -g aws-sdk
script:
- npm test
after_success:
- cd ../..
- pwd
- ls -a
- ls .ask -a
- ask deploy
